---
title: amanda grace â€“ experience design
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  works:
    title: Works
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title/"
    description:
    is_post: true
- scope:
    path: ''
    type: pages
  values:
    layout: page
    description:
- scope:
    path: ''
    type: works
  values:
    layout: work
    permalink: "/work/:title/"
    thumbnail image:
    snippet:
    description:
    question:
    summary:
    project timeframe:
    company:
permalink: pretty
breadcrumbs:
  root:
    hide: false
    image: false
